Добавляет наставника
htmlacademy-htmlcss/2067507-device-34 pull request #1
Opened 2022-05-17 16:49 UTC by M00n41ld

2022-05-18 06:22 UTC, Dima-Dim requested changes

2022-05-18 06:22 UTC, Dima-Dim commented on Readme.md
> +* Наставник: `Дмитрий Гуляев`.
Привет! Отредактируй, пожалуйста, строку Наставник чтобы было по аналогии со строкой Студент. Для этого нужно добавить ссылку на мой профиль https://htmlacademy.ru/profile/dima

2022-05-19 07:19 UTC, M00n41ld commented on Readme.md
> +* Наставник: `Дмитрий Гуляев`.
Привет! Отредактировала

2022-05-19 07:36 UTC, Dima-Dim commented on Readme.md
> +* Наставник: `Дмитрий Гуляев`.
После внесения правок не забывай отправлять задание на проверку,

2022-05-20 09:52 UTC, merged