Добавляет разметку первой страницы
htmlacademy-htmlcss/2067507-device-34 pull request #2
Opened 2022-05-22 13:35 UTC by M00n41ld

Сделала разметку первой страницы без попапов.

2022-05-23 18:16 UTC, M00n41ld commented
Первый мой пулреквест смотреть не стоит, там вообще черновик, как отозвать первый не очень поняла. Файлы во втором пулреквесте уже нормальные, готовые для проверки

2022-05-24 11:41 UTC, Dima-Dim requested changes
Не нужно использовать обёртки если их можно не использовать.
Не нужно делать кнопки input-ами.
Не нужно все изображения вставлять в разметку.

2022-05-24 11:41 UTC, Dima-Dim commented on index.html
> +    <div class="items-menu">
Точно этот div нужен?

2022-05-24 11:41 UTC, Dima-Dim commented on index.html
> +          <input type="button" Value="Каталог">
Для чего этот инпут? Какие данные мы в него будем вводить?

2022-05-24 11:41 UTC, Dima-Dim commented on index.html
> +              <a href="#" title="Виртуальная реальность"><img src="#" alt="">Виртуальная реальность</a>
Что за контентное img в меню?

2022-05-24 11:41 UTC, Dima-Dim commented on index.html
> +      <div class="numbers">
Опять div сомнительной надобности.
https://up.htmlacademy.ru/htmlcss/34/criteries#HTML-06

2022-05-24 11:41 UTC, Dima-Dim commented on index.html
> +          <input type="button" value="Подробнее">
Тоже не инпут, уже очень давно для кнопок есть специальный тег и это должно быть в ваших материалах. И чего там точно нет, дак это рекомендации использовать input для кнопок.

2022-05-24 11:41 UTC, Dima-Dim commented on index.html
> +      <div class="slider-headers">
Очень похоже на список.

2022-05-24 11:41 UTC, Dima-Dim commented on index.html
> +      <div class="slider-images">
Это части конкретных слайдом, а не изображения сами по себе.

2022-05-24 11:41 UTC, Dima-Dim commented on index.html
> +          <a href="#" title="Виртуальная реальность"><img src="#" alt="">Виртуальная реальность</a>
Здесь тоже не контентные изображения и в разметке их быть не должно.

2022-05-24 11:41 UTC, Dima-Dim commented on index.html
> +    <div class="items">
Тоже сомнительный div.

2022-05-24 11:41 UTC, Dima-Dim commented on index.html
> +      <div class="delivery">
Тоже логичнее сделать списком.

2022-05-24 11:41 UTC, Dima-Dim commented on index.html
> +          <li class="partners-list"><strong>Меловые линии</strong></li>
Сейчас мы ничего не стилизуем, тег `string` здесь явно попадает под https://up.htmlacademy.ru/htmlcss/34/criteries#HTML-06

2022-05-24 11:41 UTC, Dima-Dim commented on index.html
> +          <span class="visually-hidden">Подписаться</span>
Для чего span и класс `visually-hidden`?

2022-05-24 11:41 UTC, Dima-Dim commented on index.html
> +          <p class="footer-contacts-address-text">Санкт-Петербург, набережная реки Карповки, 5, литера П.</p>
Без p не получается?

2022-05-24 11:41 UTC, Dima-Dim commented on index.html
> +          <h4 class="visually-hidden">Навигация</h4>
Не нужно придумывать заголовков и секция для списков из 3-х пунктов.

2022-05-24 11:41 UTC, Dima-Dim commented on catalog.html
> +
Для чего пустые строки?

2022-05-24 15:22 UTC, M00n41ld commented on index.html
> +    <div class="items-menu">
думала сгруппировать элементы воедино, уберу

2022-05-24 15:25 UTC, M00n41ld commented on index.html
> +          <input type="button" Value="Каталог">
Я понимаю, что здесь что-то не то сделала, меня просто смутил значок плюсика рядом с каталогом, который меняет + на - когда открывается список, поэтому подумала мб это кнопка какая-то

2022-05-25 06:24 UTC, Dima-Dim commented on index.html
> +          <input type="button" Value="Каталог">
Это может быть кнопкой, но точне не input-ом.

2022-05-25 18:50 UTC, Dima-Dim requested changes

2022-05-25 18:50 UTC, Dima-Dim commented on catalog.html
> +      <h2 class="visually-hidden">Меню пользователя</h2>
Так себе заголовок, без него было лучше.

2022-05-25 18:50 UTC, Dima-Dim commented on catalog.html
> +        <a href="#" title="Каталог">Каталог</a>
Да, это похоже на интерактивных элемент. Но почему ссылка, будет переход на какую-то страницу?

2022-05-25 18:50 UTC, Dima-Dim commented on catalog.html
> +      <input type="button" name="up" value="Возрастание">
Опять какие-то странные инпуты. Какие данные сюда будет вводить пользователь?

2022-05-25 18:50 UTC, Dima-Dim commented on index.html
> +          <button class="button" type="button">Подробнее</button>
А вот тут как раз подразумевается переход на страницу с подробной информацией.

2022-05-25 18:50 UTC, Dima-Dim commented on index.html
> +            <button class="slider-button slider-prev" type="button">
Эти элементы не есть часть конкретного слайда, они относятся ко всему слайдеру.

2022-05-25 18:50 UTC, Dima-Dim commented on index.html
> +        <button class="button" type="button">Доставка</button>
Почему опять "элементы управления"/"меню" оказались внутри "слайдов"?

2022-05-27 09:46 UTC, Dima-Dim reviewed
Оставшиеся правки вноси в рамках следующих заданий.

2022-05-27 09:46 UTC, Dima-Dim commented on index.html
> +          <img class="delivery-icon" src="#" alt="">
`icon` - намекает на то, что это не контентное изображение и в разметку его вставлять не нужно.

2022-05-27 09:46 UTC, Dima-Dim commented on index.html
> +      <button class="button" type="button">Доставка</button>
Очень похоже на список.

2022-05-27 09:46 UTC, Dima-Dim commented on index.html
> +      <img class="car" src="#" alt="">
Скорее всего тоже какие-то не важные декоративные изображения.

2022-05-27 09:46 UTC, merged