Сетка страниц и крупных блоков на флексах
htmlacademy-htmlcss/2067507-device-34 pull request #5
Opened 2022-06-07 16:02 UTC by M00n41ld

---
:mortar_board: [Сетка страниц и крупных блоков на флексах](https://up.htmlacademy.ru/htmlcss/34/user/2067507/tasks/7)

:boom: https://htmlacademy-htmlcss.github.io/2067507-device-34/5/

2022-06-08 14:47 UTC, Dima-Dim requested changes

2022-06-08 14:47 UTC, Dima-Dim commented on catalog.html
> +                <p class="color-sorting">Цвет</p>
А если просто `legend` стилизовать?

2022-06-08 14:47 UTC, Dima-Dim commented on catalog.html
> +            <div class="pagination-container">
Почему нельзя использовать эти стили сразу на ul?

2022-06-08 14:47 UTC, Dima-Dim commented on catalog.html
> +      <div class="links-set">
Тоже вопрос про лишний div.

2022-06-08 14:47 UTC, Dima-Dim commented on index.html
> +      <!-- Здесь нужна помощь, вот этот серый фон должен тянуться на всю ширину экрана, но у меня он ограничен моим свойством page-container : 1060. как сделать ширину так, чтобы она тянулась не пони
Убрать page-container, потому что такой способ тут не подходит.

2022-06-08 14:51 UTC, Dima-Dim commented on index.html
> +          <!--В фигме в этом блоке еще лежат кнопки переключения слайдеров, я их пока оставляю там где они сейчас есть или уже время переделывать их и ставить внутрб этого блока?-->
Можно заняться этим после материала про декоративные элементы.

2022-06-08 14:51 UTC, Dima-Dim commented on index.html
> +      <!--Нужно ли разнести это тоже при помощи флексов? В барбершопе подобное сделано, но мне кажется, что кол-во элементов может поменяться и это мелкий блок-->
Да, количество элементов может поменяться и тебе нужно решить как это сделать удобнее, чтобы при переполнение он вёл себя более предсказуемо.

2022-06-08 15:07 UTC, M00n41ld commented on index.html
> +      <!--Нужно ли разнести это тоже при помощи флексов? В барбершопе подобное сделано, но мне кажется, что кол-во элементов может поменяться и это мелкий блок-->
Думаю, я это сделаю в след блоке, где расскаывается про мелкие сетки и переполнение

2022-06-12 04:41 UTC, Dima-Dim requested changes

2022-06-12 04:41 UTC, Dima-Dim commented on index.html
> +    <div class="sliders">
Ты даже класс правильно назвала `sliders` - понимая что должен быть контейнер для слайдов, их же много, прям как пунктов меню, например, но внутри только один элемент, т.е. слайд.

2022-06-12 04:41 UTC, Dima-Dim commented on index.html
> +    <div class="icons-catalog-list">
Для чего этот контейнер? Почему стили с `icons-catalog-list` не получается разместить в `items-list`?

2022-06-12 04:41 UTC, Dima-Dim commented on index.html
> +    <div class="services-options">
Вот тут в контейнере может быть смысл, потому что он объединяет 2 списка.

2022-06-12 04:41 UTC, Dima-Dim commented on index.html
> +    <section class="rare-delivery">
Если section состоит только их заголовка, то это не section, а просто заголовок, а может и просто текст, потому что заголовок озаглавливает что-то.

2022-06-13 04:08 UTC, Dima-Dim commented
Надеюсь остальное поправишь в следующих заданиях.

2022-06-13 04:08 UTC, merged