Добавляет 9 задание
htmlacademy-htmlcss/2067507-device-34 pull request #8
Opened 2022-06-27 18:19 UTC by M00n41ld

2022-06-28 02:51 UTC, Dima-Dim requested changes

2022-06-28 02:51 UTC, Dima-Dim commented on catalog.html
> +            <button class="arrows" type="button">
https://up.htmlacademy.ru/htmlcss/34/criteries#ALLY-02 касается всех интерактивных элементов, у которых нет текстового описания.

2022-06-28 02:51 UTC, Dima-Dim commented on catalog.html
> +                <a class="pagination-link pagination-current" href="#">
`pagination-current` я так понимаю и есть стили для текущей страницы из стайлгайда.

2022-06-28 02:51 UTC, Dima-Dim commented on index.html
> +            <svg class="icons-block" aria-hidden="true" focusable="false" width="97" height="55" viewBox="0 0 97 55"
Для чего это svg в разметке?

2022-06-28 02:51 UTC, Dima-Dim commented on styles/styles.css
> +/*Как сделать фокус квадратной рамочкой, а не как у меня по бордеру?*/
Например, можно попробовать использовать тени.

2022-06-28 02:51 UTC, Dima-Dim commented on styles/styles.css
> +.svg-container {
Судя по названию прям для всех svg контейнер.

2022-06-28 02:51 UTC, Dima-Dim commented on styles/styles.css
> +  height: 319px;
Если кнопок будет больше, то высота этого элемента никак не изменится, я полагаю. С одной стороны не критично, с другой хорошо бы и такие моменты тоже продумывать.

2022-06-28 02:51 UTC, Dima-Dim commented on styles/styles.css
> +  height: 57px;
А здесь вообще высота приведёт к проблемам с переполнением. Не забудь решить далее.

2022-06-28 02:51 UTC, Dima-Dim commented on styles/styles.css
> +/* не понимаю как вообще здесь сделать состояния, потому что если я делаю opacity то и текст тоже становится прозрачным, вможет здесь вообще какой-то друго способ нужен?*/
Начать можно с того, что Подробнее это не декоративный текст, а очень даже важный интерактивный элемент. Т.е. нужно доработать вёрстку, как стало понятно теперь, элементы с опасити должен быть отделён от элемента на который это опасити распространяться не должно. собственно именно в таких моментах и проявляется сложность этого проекта.

2022-06-28 02:51 UTC, Dima-Dim commented on styles/styles.css
> +  content: "Подробнее";
Нет, это должно быть в разметке и с этим пользователь должен иметь возможность взаимодействовать.

2022-06-28 14:58 UTC, M00n41ld commented on styles/styles.css
> +  height: 319px;
Логика понятна, вопрос в том, как избежать указания высоты тут, потому что это псевдоэлемент без контента, и если я ему не указу высоту - он схлопнется

2022-06-29 01:28 UTC, Dima-Dim commented on styles/styles.css
> +  height: 319px;
> если я ему не укажу высоту - он схлопнется.

Я не говорил что высоту тут указывать не нужно :)

2022-06-29 03:49 UTC, Dima-Dim requested changes

2022-06-29 03:49 UTC, Dima-Dim commented on catalog.html
> +        <!--Правильно ли я поставила подпись для скринридера?-->
Вот тут https://up.htmlacademy.ru/htmlcss/34/criteries#HTML-05 рассказано как правильно.

2022-06-29 03:49 UTC, Dima-Dim commented on catalog.html
> +                  <button type="button" class="card-info button">Подробнее</button>
Почему именно button?

2022-06-29 03:49 UTC, Dima-Dim commented on index.html
> +          <!--Переделываю на кнопку, тк в стайлгайде у нее есть состояние disabled-->
Разве это должно влиять на выбор между ссылкой или кнопкой?

2022-06-29 03:49 UTC, Dima-Dim commented on index.html
> +          <button class="button current-button" type="button">
Вот здесь к кнопкам вопросов нет.

2022-06-29 03:49 UTC, Dima-Dim commented on index.html
> +        <!--Нужно ли для этх псевднокнопок прописывать disabled?-->
Что значит псевдокнопки? :) Ну и для того, чтобы принять решение по этому вопросу, нужно подумать, а может ли понадобиться такое состояние? Да и даже вдруг нет, то реализовать такое состояние не должно быть проблемой, чтобы не возникло вопросов в будущем.

2022-06-29 03:49 UTC, Dima-Dim commented on styles/styles.css
> +Сделать рамку при помощи box shadow не получилось, какие еще есть варианты?*/
Не получилось что именно? Какой код для этого был использован?

2022-06-29 03:49 UTC, Dima-Dim commented on styles/styles.css
> +  height: 61px;
Тут да, это же input и он однострочный.

2022-06-29 03:49 UTC, Dima-Dim commented on styles/styles.css
> +/*Почему-то именно полоска берет себе opacity, а текст нет, такой же черный как и должен быть, где косяк - не вижу*/
Нужно смотреть вложенность элементов и применённые к ним стили браузером в девтулзах. Из этой информации должно быть наглядно понятно что и почему.

2022-06-30 15:06 UTC, Dima-Dim commented on catalog.html
>                      <h3 class="product-card-title">Любительская <br>селфи-палка</br></h3>
Тут либо я либо ты пропустили br, явно не нужный.

2022-06-30 15:06 UTC, merged

2022-06-30 15:08 UTC, M00n41ld commented on catalog.html
>                      <h3 class="product-card-title">Любительская <br>селфи-палка</br></h3>
Если убрать - то не так как на макете, можно задать фикс ширину блоку, так лучше будет?

2022-06-30 15:17 UTC, Dima-Dim commented on catalog.html
>                      <h3 class="product-card-title">Любительская <br>селфи-палка</br></h3>
Да, шириной должно быть лучше.